category: TRAVEL_AND_TRANSPORTATION
defaultLocale: ko
enabledRegions:
- South Korea
localizedSettings:
  developerEmail: hijae@cu.ac.kr
  developerName: hijae
  displayName: 대구가대 안심역 버스
  fullDescription: |-
    대구가톨릭대학교 안심역 스쿨 버스의 시간을 알려줍니다.
    등교 시간과 하교 시간을 지원하고 가장 가까운 버스를 알려줍니다.
    (2022.2 기준)
    ( 대가대 , 대구가대 , 대구가톨릭대학교 )
  privacyPolicyUrl: https://sites.google.com/view/dcubuspp
  pronunciation: 대구가대 안심역 버스
  sampleInvocations:
  - 대구가대 안심역 버스한테 말하기
  shortDescription: 대구가톨릭대학교 안심역 스쿨 버스 시간을 알려줍니다.
  smallLogoImage: https://lh3.googleusercontent.com/L51Yf4GsfGFGbWsje8wCFEK3xQGHJhs1tczGOqv3kE7ZAF9BbRMZIbbz-e8h7ZD6poiAMTC_IOD6
  themeCustomization:
    backgroundColor: '#FAFAFA'
    imageCornerStyle: CURVED
    primaryColor: '#29589E'
  voice: female_1
projectId: dcubus-38923
